markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "诗酒趁年华"
markdown: rdiscount

author: "Theodoer"
atom-baseurl: "http://theodoer.github.io"
disqus: "Theodoer"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

